- name: Check open ports
  command:  bash -c "netstat -ntlp | awk '{print $4}' | grep '0.0.0.0'"
  register: open_ports

- name: Create report file
  delegate_to: 127.0.0.1
  run_once: true
  template: 
    src: report.j2
    dest: "{{ playbook_dir }}/report.txt"
  #tags: tor, report

