---
- name: Install Pkgs
  apt: name={{ item }} state=installed update_cache=true cache_valid_time=864000
  with_items: 
    - sudo 
    - build-essential
    - gettext
    - unzip
    - expect
    - python2.7-dev
    - python-pip
    - python-mysqldb
    - libjpeg8-dev
    - libtiff-dev
    - libjpeg-dev
    - python-virtualenv
    - libmysqlclient-dev
    - git
    - supervisor
    - nginx
    - tor
    - mysql-server
    - redis-server
  tags: common

- name: Create user
  user:
    name: "{{ user_name }}"
    state: present
    password: "{{ user_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: "sudo"
    createhome: yes
  tags: common, user

